#!/usr/bin/env bash

name=${DB_NAME-"chimera"}
host=${DB_HOST-"localhost"}
username=${DB_USERNAME-"dana"}

for i in `ls -v migrations/*.up.sql`; do
  echo "Applying migration: $i"
  psql -d $name -h $host -U $username -f $i
done
