#!/usr/bin/env node

const Activity = require('../server/models/activity')
const chalk = require('chalk')
const config = require('config')
const Event = require('../server/models/event')
const Instructor = require('../server/models/instructor')
const User = require('../server/models/user')

console.log(chalk.green('Seeding database...'))

async function seed() {

  const welding = await Event.create({
    title: 'Intro to Welding',
    description: 'This will be fun!',
    //photo_url: '',
    //meetup_url: '',
    draft: false,
    internal: false,
    category: 'class',
    attendeeMin: 8,
    attendeeMax: 10,
    price: 15000,
    memberPrice: 13500,
    materialFee: 2000,
    startsAt: new Date('2017-04-23T17:00:00Z'),
    endsAt: new Date('2017-04-23T23:00:00Z'),
  })

  const jewelry = await Event.create({
    title: 'Jewelry Training',
    description: 'Making rings and shit',
    //photo_url: '',
    //meetup_url: '',
    draft: true,
    internal: true,
    category: 'training',
    attendeeMin: 3,
    attendeeMax: 5,
    price: 3599,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-04-28T17:00:00Z'),
    endsAt: new Date('2017-04-28T19:00:00Z'),
  })

  const laser = await Event.create({
    title: 'Laser Cutter Training',
    description: 'LASERS!',
    //photo_url: '',
    //meetup_url: '',
    draft: false,
    internal: true,
    category: 'training',
    attendeeMin: 3,
    attendeeMax: 5,
    price: 3500,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-05-02T02:30:00Z'),
    endsAt: new Date('2017-05-02T04:30:00Z'),
  })

  const printing = await Event.create({
    title: '3D Printing Meetup',
    description: `Nulla vitae elit libero, a pharetra augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

Donec sed odio dui. Curabitur blandit tempus porttitor. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.`,
    //photo_url: '',
    //meetup_url: '',
    draft: false,
    internal: false,
    category: 'meetup',
    attendeeMin: null,
    attendeeMax: null,
    price: null,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-06-08T00:00:00Z'),
    endsAt: new Date('2017-06-08T02:00:00Z'),
  })




  const dana = await User.create({
    name: 'Dana Woodman',
    email: 'dana@chimeraarts.org',
    staff: true,
  })

  const kimberly = await User.create({
    name: 'Kimberly Mullen',
    email: 'kimberly@chimeraarts.org',
  })

  const jim = await User.create({
    name: 'Jim Wheaton',
    email: 'jim@chimeraarts.org',
  })

  const briona = await User.create({
    name: 'Briona Hendren',
    email: 'briona@chimeraarts.org',
  })




  await Instructor.create({
    eventId: welding.id,
    userId: dana.id,
  })

  await Instructor.create({
    eventId: welding.id,
    userId: briona.id,
  })

  await Instructor.create({
    eventId: jewelry.id,
    userId: kimberly.id,
  })

  await Instructor.create({
    eventId: printing.id,
    userId: jim.id,
  })



  await Activity.record({
    action: 'updated',
    model: welding,
    user: dana,
  })


  console.log(chalk.green('Successfully seeded database!'))

  process.exit()
}

seed()

