#!/usr/bin/env node

const Activity = require('../server/models/activity')
const Attendee = require('../server/models/attendee')
const chalk = require('chalk')
const config = require('config')
const Event = require('../server/models/event')
const Instructor = require('../server/models/instructor')
const Charge = require('../server/models/charge')
const User = require('../server/models/user')

console.log(chalk.green('Seeding database...'))

async function seed() {

  const past = await Event.create({
    title: 'Past Event',
    description: 'Old event',
    //photo_url: '',
    draft: false,
    internal: false,
    category: 'event',
    attendeeMax: 100,
    meetupId: 9393,
    startsAt: new Date('2016-09-12T12:00:00Z'),
    endsAt: new Date('2016-09-12T23:00:00Z'),
  })

  const welding = await Event.create({
    title: 'Intro to Welding',
    description: 'This will be fun!',
    //photo_url: '',
    draft: false,
    internal: false,
    category: 'class',
    attendeeMin: 8,
    attendeeMax: 10,
    price: 15000,
    memberPrice: 13500,
    materialFee: 2000,
    meetupId: 1234,
    startsAt: new Date('2017-09-23T17:00:00Z'),
    endsAt: new Date('2017-09-23T23:00:00Z'),
  })

  const jewelry = await Event.create({
    title: 'Jewelry Training',
    description: 'Making rings and shit',
    //photo_url: '',
    draft: true,
    internal: true,
    category: 'training',
    attendeeMin: 3,
    attendeeMax: 5,
    price: 3599,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-09-28T17:00:00Z'),
    endsAt: new Date('2017-09-28T19:00:00Z'),
  })

  const laser = await Event.create({
    title: 'Laser Cutter Training',
    description: 'LASERS!',
    //photo_url: '',
    draft: false,
    internal: true,
    category: 'training',
    attendeeMin: 3,
    attendeeMax: 5,
    price: 3500,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-11-02T02:30:00Z'),
    endsAt: new Date('2017-11-02T04:30:00Z'),
  })

  const printing = await Event.create({
    title: '3D Printing Meetup',
    description: `Nulla vitae elit libero, a pharetra augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ullamcorper nulla non metus auctor fringilla. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.

Donec sed odio dui. Curabitur blandit tempus porttitor. Donec sed odio dui. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.`,
    //photo_url: '',
    draft: false,
    internal: false,
    category: 'meetup',
    attendeeMin: null,
    attendeeMax: null,
    price: null,
    memberPrice: null,
    materialFee: null,
    startsAt: new Date('2017-12-08T00:00:00Z'),
    endsAt: new Date('2017-12-08T02:00:00Z'),
  })

  const full = await Event.create({
    title: 'Full Event',
    description: `This is full`,
    category: 'class',
    attendeeMin: null,
    attendeeMax: 1,
    startsAt: new Date('2017-12-08T00:00:00Z'),
    endsAt: new Date('2017-12-08T02:00:00Z'),
  })




  const dana = await User.create({
    name: 'Dana Woodman',
    email: 'dana@chimeraarts.org',
    staff: true,
    stripeCustomerId: 'cus_ASCAicaPwBtUnb',
    bio: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.',
  })

  const kimberly = await User.create({
    name: 'Kimberly Mullen',
    email: 'kimberly@chimeraarts.org',
  })

  const jim = await User.create({
    name: 'Jim Wheaton',
    email: 'jim@chimeraarts.org',
  })

  const briona = await User.create({
    name: 'Briona Hendren',
    email: 'briona@chimeraarts.org',
  })




  await Instructor.create({
    eventId: welding.id,
    userId: dana.id,
  })

  await Instructor.create({
    eventId: welding.id,
    userId: briona.id,
  })

  await Instructor.create({
    eventId: jewelry.id,
    userId: kimberly.id,
  })

  await Instructor.create({
    eventId: printing.id,
    userId: jim.id,
  })


  const t1 = await Charge.create({
    amount: 4599,
    stripeChargeId: 'asdf',
    type: Charge.CARD,
    lastFour: 1234,
    memo: 'here is a note',
    userId: dana.id,
  })
  await Attendee.create({
    eventId: welding.id,
    chargeId: t1.id,
    userId: dana.id,
  })

  const t2 = await Charge.create({
    amount: 400,
    type: Charge.CASH,
    memo: 'Paid day of event',
    userId: jim.id,
  })
  await Attendee.create({
    eventId: welding.id,
    chargeId: t2.id,
    userId: jim.id,
  })

  const t3 = await Charge.create({
    amount: 2945,
    type: Charge.CHECK,
    checkNumber: '2012341',
    userId: kimberly.id,
  })
  await Attendee.create({
    eventId: welding.id,
    chargeId: t3.id,
    userId: kimberly.id,
  })

  const t4 = await Charge.create({
    amount: 400,
    type: Charge.CASH,
    userId: kimberly.id,
  })
  await Attendee.create({
    eventId: full.id,
    chargeId: t4.id,
    userId: kimberly.id,
  })

  await Activity.record({
    action: 'updated',
    model: welding,
    user: dana,
  })


  console.log(chalk.green('Successfully seeded database!'))

  process.exit()
}

seed()

